### PR TITLE
ENH: Add vmin and vmax to viewer

### LINKED ISSUE #723: vmin and vmax viewer properties set color range
I don't know how to wrap get/set of color range with matplotlib like vmin and vmax properties.  How to do synchronous wrapping of async Viewer methods?

Goal is something like adding this to Viewer class
```
    @property
    def vmin(self):
        range = self.get_image_color_range()
        return range[0]
    @vmin.setter
    def vmin(self, vmin):
        range = self.get_image_color_range()
        range[0] = vmin
        self.set_image_color_range(range)
```

### PR DESCRIPTION
**Pull request by PaulHax**
Closes #723

Depends on:
https://github.com/Kitware/itk-vtk-viewer/pull/730#pullrequestreview-1793586609

### CODE REVIEW

**Review by thewtex — COMMENTED** [review]
Nice!

@bnmajor if / when we have an inherited ipywidget viewer class, they will be able to override these properties with the traitlets, correct?

@PaulHax could you please also add `vmin`, `vmax` arguments to `view`?

**Comment by bnmajor** [comment]
> @bnmajor if / when we have an inherited ipywidget viewer class, they will be able to override these properties with the traitlets, correct?

Yup! Essentially you would just swap out `property` for `observe` and `val.setter` for `default("val")`. For example:

```
class Foo:
    ....
     @property
     def bar(self):
             return self.get_value()

     @bar.setter
     def bar(self, val):
             self.set_value(val)
```

should become

```
class Foo(HasTraits):
    bar = Int()

     @observe
     def bar(self):
             return self.get_value()

     @default("bar")
     def bar(self, val):
             self.set_value(val)
```

**Review by thewtex — APPROVED** [review]
:+1: please bump the itk-vtk-viewer version before merge

**Comment by thewtex** [comment]
tagging

**Pull request merged**
