### PR TITLE
Downsample label

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
Closes #532

**Comment by bnmajor** [comment]
@thewtex I'm noticing some weirdness when I run the rt_struct notebook.... The image and label map are rendered but they're not centered. In Jupyter Lab:

weird_loading_1

In SageMaker:

weird_loading_2

I didn't see this when I tried the transform_visualization notebook with the label image.

**Comment by PaulHax** [comment]
Looks like an itk-vtk-viewer issue.  Where do I get this troublemaker notebook?

**Comment by bnmajor** [comment]
@PaulHax I will get you a copy!

**Comment by thewtex** [comment]
It turns out the `dim` order was reserved in the higher scales, which was causing the wackiness. Addressed here: https://github.com/spatial-image/multiscale-spatial-image/pull/67

**Comment by thewtex** [comment]
@bnmajor please give it another try.

**Review by bnmajor — APPROVED** [review]
@thewtex Works perfectly now, thanks!

**Pull request merged**
