### PR TITLE
ENH: Also test 2DImage.ipynb notebook in CI

### PR DESCRIPTION
**Pull request by thewtex**
@alex-treebeard

### CODE REVIEW

**Comment by thewtex** [comment]
:+1: renamed

**Comment by thewtex** [comment]
@alex-treebeard the action appears to try all notebooks, even though only the first two are specified in *treebeard.yaml*.

```
+ pip install -U git+https://github.com/treebeardtech/treebeard.git@master#subdirectory=treebeard-lib
+ treebeard run --no-use-docker --no-upload --usagelogging --confirm
🌲  Running locally without docker using your current python environment
19:51:01: 🌲 treebeard runtime: running repo
Will run the following:
 - examples/2DImage.ipynb
 - examples/3DImage.ipynb
 - examples/CameraParameters.ipynb
 - examples/Checkerboard.ipynb
 - examples/CompareImages.ipynb
 - examples/DaskArray.ipynb
 - examples/ImageJImgLib2.ipynb
 - examples/ImageWithAnisotropicPixelSpacing.ipynb
 - examples/InteractiveParameterExploration.ipynb
 - examples/LabelImages.ipynb
 - examples/LargeVolumes.ipynb
 - examples/LineProfile.ipynb
 - examples/Mayavi.ipynb
 - examples/Mesh.ipynb
 - examples/NumPyArrayImage.ipynb
 - examples/NumPyArrayPointSet.ipynb
[...]
```

**Comment by alex-treebeard** [comment]
ah not sure why this is happening. Thanks for the heads up.

Will take a look at this tomorrow.

**Comment by alex-treebeard** [comment]
Just put in a fix + test for this

Should work if you hit rerun, but I'd recommend you also point to the release i have just made as master will be less stable:

` - uses: treebeardtech/treebeard@v0.1.1`

(as used here https://github.com/alex-treebeard/itkwidgets/actions/runs/179882847/workflow)

**Comment by thewtex** [comment]
@alex-treebeard thanks! Pointing to `treebeard@v0.1.1`.

**Pull request merged**
