### PR TITLE
Image label

### PR DESCRIPTION
**Pull request by bnmajor**
Add support for labels

Relies on Kitware/itk-vtk-viewer#522

### CODE REVIEW

**Comment by bnmajor** [comment]
This is currently still marked as a draft because in some of my testing I am seeing the label rendering take so long it is essentially unusable (~4-5 minutes). In other cases I am not seeing this issue though (it may be seconds slow but not minutes) but in both cases it seems to spend most of the time in [`toMultiscaleSpatialImage`](https://github.com/Kitware/itk-vtk-viewer/blob/master/src/IO/toMultiscaleSpatialImage.js#L39-L82).

**Comment by PaulHax** [comment]
> label rendering take so long it is essentially unusable (~4-5 minutes)

itk-vtk-viewer state machine can get loopy off the golden path.  I'm happy to try to reproduce in JS on https://github.com/Kitware/itk-vtk-viewer/pull/522 if you like.

**Comment by thewtex** [comment]
@PaulHax yes, please take a look :pray:

**Comment by bnmajor** [comment]
@PaulHax Thanks, I appreciate it!

**Pull request merged**
