### PR TITLE
ENH: add animate image mix button via bootstrap-ui

### PR DESCRIPTION
**Pull request by PaulHax**

### CODE REVIEW

**Comment by bnmajor** [comment]
@PaulHax Thanks, this is very cool! Works well for me!

I tested this with the `ThinPlateSpline` notebook and the visualization wasn't loading in the last cell and I am seeing errors in the console:
```
BloscZarr.umd.js:1 failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
o.printErr @ BloscZarr.umd.js:1
BloscZarr.umd.js:1 Aborted(RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance)
```
I know this is not related to the bootstrap changes but I'm curious if you've seen this before?

**Review by bnmajor — APPROVED** [review]
Awesome!!

**Review by thewtex — APPROVED** [review]
:sparkling_heart:

**Comment by PaulHax** [comment]
@bnmajor 

I've not seen that error in that context.  3 viewers on a page might be too much.

**Pull request merged**
